### ISSUE TITLE
Compile error for generated template function in proxy

### ISSUE THREAD

**Issue by zxtwonder** [Pelagicore/gdbus-codegen-glibmm#28]
First of all, thank you so much for providing this great utility. There seems to be trivial issue with the generated template function.

Input method schema:
```xml
        <method name="SetProperty">
            <arg name="name" type="s" direction="in"/>
            <arg name="value" type="v" direction="in"/>
        </method>
```
Generated proxy template function (indent as generated):
```cpp
    template <typename T>
    void SetProperty(
        std::string name,
        T value,
        const Gio::SlotAsyncReady &callback)
    {
        Glib::VariantContainerBase base;
        std::vector<Glib::VariantBase> params;
        Glib::Variant<Glib::ustring> name_param = Glib::Variant<Glib::ustring>::create(arg_name);
        params.push_back(name_param);
        Glib::Variant<Glib::Variant<T> > value_variantValue;
        value_variantValue = Glib::Variant<Glib::Variant<T> >::create(Glib::Variant<T>::create(value_param));
        params.push_back(value_variantValue);
        base = Glib::VariantContainerBase::create_tuple(params);

    m_proxy->call(
        "SetProperty",
        callback,
        base);
}
```

Comparing the generated template function and other functions, it seems that the function argument naming and the variantValue reference are inconsistent. Is it correct that the template function should be generated as the following?

```cpp
    template <typename T>
    void SetProperty(
        std::string arg_name,
        T arg_value,
        const Gio::SlotAsyncReady &callback)
    {
        ...
        Glib::Variant<Glib::ustring> name_param = Glib::Variant<Glib::ustring>::create(arg_name);
        ...
        value_variantValue = Glib::Variant<Glib::Variant<T> >::create(Glib::Variant<T>::create(arg_value));
        ...
```

Related code: https://github.com/Pelagicore/gdbus-codegen-glibmm/blob/35bef0fab90efa2635c037fd6804eddb13063852/codegen_glibmm/codegen.py#L149

**Comment by mardy** [comment]
Hi @zxtwonder! Thanks for you bug report, indeed it looks like the generated files are wrong; it's a bit strange that we didn't catch this bug before.

Yes, it looks like a silly naming issue, and your suggestion should work.

**Comment by zxtwonder** [comment]
Mistakenly closed from my fork. Reopened.
