### ISSUE TITLE
*MessageHelper and *TypeWrap in commoh.h.templ not namespaced

### ISSUE THREAD

**Issue by martin-ejdestig** [Pelagicore/gdbus-codegen-glibmm#55]
Unsure why they are put in the global namespace.

Could namespace or perhaps better yet, nest TypeWrap in proxy and MessageHelper in stub.

Is it OK to change this? (Do not know what policy is with regards to backwards compatibility.) I can send a patch if it's OK and you tell me what you prefer.

I think nesting is better. I do not see why they are in common.h.templ. Not used in both proxy and stub. Am I missing something?

**Comment by kursatkobya** [comment]
I have checked proxies that we are used in other projects and agree with you that we do not use MessageHelper

**Comment by martin-ejdestig** [comment]
I am also thinking that "MessageHelper" should be renamed to e.g. "Invocation" since it wraps a Gio::DBus::MethodInvocation that itself has a get_message() method for returning a Gio::DBus::Message. (Confusing to mix concepts.)

**Comment by kursatkobya** [comment]
I am working on this.

**Comment by martin-ejdestig** [comment]
I am running into problems with this now. An external project has an interface that ends with .Foo and I want to have an interface that ends with .Foo as well. Will look into picking up #59 tomorrow.

(Original problem I had was that I ran in to #57 , but thought it was better to have Bar.Foo instead of BarFoo . Do not know how to fix #57 though without breaking API.)

**Comment by martin-ejdestig** [comment]
Fixed by #59. Closing.
