### ISSUE TITLE
Make stub instances exportable over multiple object paths and connections

### ISSUE THREAD

**Issue by mardy** [Pelagicore/gdbus-codegen-glibmm#81]
While not very common, there are cases where one might want to export the very same object over two different object paths. Also, especially when dealing with clients connecting directly to the service over a socket connection (bypassing the D-Bus daemon), it should be possible to export the same object over two different connections (on the same or on a different object path).

**Comment by martin-ejdestig** [comment]
From #78 :

> Would have to store a list of:
> 
>     - registered object id:s to get automatic de-registration on destruction.
>     - object paths for iterating over when doing signal emission... right?
